// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rawbit.Data.DbContext;

#nullable disable

namespace Rawbit.Migrations
{
    [DbContext(typeof(RawbitProjectContext))]
    [Migration("20260215123000_AddLightAdjustments")]
    partial class AddLightAdjustments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Rawbit.DataContext.Adjustments", b =>
                {
                    b.Property<Guid>("AdjustmentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Exposure")
                        .HasColumnType("REAL");

                    b.Property<float>("Highlights")
                        .HasColumnType("REAL");

                    b.Property<float>("Shadows")
                        .HasColumnType("REAL");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<float>("Tint")
                        .HasColumnType("REAL");

                    b.HasKey("AdjustmentsId");

                    b.ToTable("Adjustments");
                });

            modelBuilder.Entity("Rawbit.DataContext.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdjustmentsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImageId");

                    b.HasIndex("AdjustmentsId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Rawbit.DataContext.Image", b =>
                {
                    b.HasOne("Rawbit.DataContext.Adjustments", "Adjustments")
                        .WithMany()
                        .HasForeignKey("AdjustmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adjustments");
                });
#pragma warning restore 612, 618
        }
    }
}
